### ISSUE TITLE
Move the hazelnut selector in the builder.

### ISSUE THREAD

**Issue by Ner-f** [SvarturH/legendhub#142]
## Expected Behavior

The hazelnut selector should be after the amulet selector in injdex.ejs

## Current Behavior

The live version has the amulet selector BEFORE the hazelnut selector. I'm proposing a change to fix that.

## Possible Solution

Move the hazelnut selector to show up after the amulet selector.

## Steps to Reproduce (for bugs)

n/a

## Your Environment

* Version used: 2.5
* Browser Name and version: Chrome Version 110.0.5481.177
* Operating System and version (desktop or mobile): Desktop, Windows 11
* Link to your project:

**Comment by steventhorne** [comment]
Fixes an issue in #138 #139

**Comment by steventhorne** [comment]
Fixed in #143
